export enum EColumn {
        Id          = 1,
        Complex     = 2,
        Coordinates = 3,
        Address     = 4,
        Money       = 5,
        RoomCount   = 6,
        Info        = 7,
        Link        = 8,
        Description = 9,
        Phone       = 10,
        View        = 11,
        Note        = 12,
        Images      = 13,
}
